[
  {
    estudante_id: 1,
    curso_id: 1,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 1,
    curso_id: 2,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 1,
    curso_id: 5,
    status: 'cancelado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 2,
    curso_id: 7,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 2,
    curso_id: 8,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 2,
    curso_id: 3,
    status: 'cancelado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 3,
    curso_id: 3,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 4,
    curso_id: 4,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 4,
    curso_id: 5,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 5,
    curso_id: 3,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    estudante_id: 5,
    curso_id: 4,
    status: 'matriculado',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
